## code to prepare `table_reference` dataset goes here

table_reference <- tribble(
  ~table_name, ~ original_column, ~ rename_column, ~ data_category, ~ data_type,
  "lexis", "xcasenum", "case_id", "case_info", "character",
  "lexis", "xfiledate", "filing_date", "case_info", "character",
  "lexis", "xfileyear", "filing_year", "extra_case_info", "character",
  "lexis", "xfilemonth", "filing_month", "extra_case_info", "character",
  "lexis", "xfileday", "filing_day", "extra_case_info", "character",
  "lexis", "xfileweek", "filing_week", "extra_case_info", "character",
  "lexis", "xcourtco", "court_county", "case_info", "character",
  "lexis", "xcourtcofips", "court_county_fips", "case_info", "character",
  "lexis", "xdefendant", "defendant_name", "case_info", "character",
  "lexis", "xplaintiff", "plaintiff_name", "case_info", "character",
  "lexis", "xdefendant_number", "geocodio_street_number", "defendant_address", "character",
  "lexis", "xdefendant_street_predirectional", "geocodio_pre_direction", "defendant_address", "character",
  "lexis", "xdefendant_street_only", "geocodio_street_name", "defendant_address", "character",
  "lexis", "xdefendant_street_suffix", "geocodio_street_suffix", "defendant_address", "character",
  "lexis", "xdefendant_street", "geocodio_full_street_name", "defendant_address", "character",
  "lexis", "xdefendant_secondaryunit", "geocodio_unit_type", "defendant_address", "character",
  "lexis", "xdefendat_secondarynumber", "geocodio_unit", "defendant_address", "character",
  "lexis", "xdefendant_city", "geocodio_city", "defendant_address", "character",
  "lexis", "xdefendant_state", "geocodio_state", "defendant_address", "character",
  "lexis", "xdefendant_address", "geocodio_full_address", "defendant_address", "character",
  "lexis", "xplaintiff_address", "plaintiff_full_address", "extra_case_info", "character",
  "lexis", "GEOID.accuracy", "geocodio_accuracy", "defendant_address", "character",
  "lexis", "GEOID.accuracy_type", "geocodio_accuracy_type", "defendant_address", "character",
  "lexis", "GEOID.longitude", "geocodio_longitude", "defendant_address", "character",
  "lexis", "GEOID.latitude", "geocodio_latitude", "defendant_address", "character",
  "lexis", "GEOID.State", "geocodio_state_fips", "defendant_address", "character",
  "lexis", "GEOID.County", "geocodio_county_fips", "defendant_address", "character",
  "lexis", "GEOID.Tract", "geocodio_tract", "defendant_address", "character",
  "lexis", "GEOID.Block", "geocodio_block", "defendant_address", "character",
  "lexis", "GEOID.Zip", "geocodio_zip", "defendant_address", "character",
  "lexis", "sealed", "sealed", "internal", "character",
  "lexis", "commercial", "commercial", "internal", "character",
  "lexis", "dup", "duplicate", "internal", "character",
  "lexis", "case_dup",  "dupe_case_id", "internal", "character",
  "lexis", "anon",  "anon", "internal", "character",
  "lexis", "xsite",  "data_source", "internal", "character",
  "lexis", "include", "include", "internal", "character",
  "lexis", "Add/Change/Delete Flag", "flag", "internal", "character",
  "lexis", "INDIVBUSUN + AKA_YN", "idk", "extra_case_info", "character",
  "lexis", "ASSOCCODE", "idk_code", "extra_case_info", "character",
  "lexis", "COURTID", "court_id", "case_info", "character",
  "lexis", "FILETYPEID", "filing_type", "case_info", "character",
  "lexis", "CASENUMBER", "raw_case_id", "extra_case_info", "character",
  "lexis", "BOOK", "book", "extra_case_info", "character",
  "lexis", "PAGE", "page", "extra_case_info", "character",
  "lexis", "ACTIONDATE", "raw_filing_date", "extra_case_info", "character",
  "lexis", "RELEASEDATE", "raw_release_date", "extra_case_info", "character",
  "lexis", "AMOUNT", "claim_amount", "case_info", "character",
  "lexis", "ASSETS", "assets", "extra_case_info", "character",
  "lexis", "PLAINTIFF", "raw_plaintiff_name", "extra_case_info", "character",
  "lexis", "ATTORNEY", "attorney_name", "extra_case_info", "character",
  "lexis", "Original Court ID", "original_court_id", "extra_case_info", "character",
  "lexis", "S341DATE", "S341_date", "extra_case_info", "character",
  "lexis", "JUDGE", "judge_name", "extra_case_info", "character",
  "lexis", "OTHERCASE", "other_case", "extra_case_info", "character",
  "lexis", "SSN", "ssn", "extra_case_info", "character",
  "lexis", "Defendant Name", "raw_defendant_name", "extra_case_info", "character",
  "lexis", "GENERATION", "generation", "extra_case_info", "character",
  "lexis", "ADDRESS", "lexis_address", "defendant_address", "character",
  "lexis", "CITY", "lexis_city", "defendant_address", "character",
  "lexis", "STATE", "lexis_state", "defendant_address", "character",
  "lexis", "ZIP", "lexis_zip", "defendant_address", "character",
  "lexis", "UPLOADDATE", "upload_date", "extra_case_info", "character",
  "lexis", "UNLAWDETYN", "unlaw_idk", "extra_case_info", "character",
  "lexis", "ORIGCASE", "original_case", "extra_case_info", "character",
  "lexis", "ORIGBOOK", "original_book", "extra_case_info", "character",
  "lexis", "ORIGPAGE", "original_page", "extra_case_info", "character",
  "lexis", "Attorney Address", "attorney_address", "extra_case_info", "character",
  "lexis", "Attorney City",  "attorney_city", "extra_case_info", "character",
  "lexis", "Attorney State", "attorney_state", "extra_case_info", "character",
  "lexis", "Attorney Zip Code",  "attorney_zip", "extra_case_info", "character",
  "lexis", "Assets Available",  "assets_available", "extra_case_info", "character",
  "lexis", "ACTIONTYPE",  "action_type_id", "extra_case_info", "character",
  "lexis", "S341TIM", "S341_idk", "extra_case_info", "character",
  "lexis", "CTYRESID", "city_resident_id", "extra_case_info", "character",
  "lexis", "Orig Dept", "original_dept", "extra_case_info", "character",
  "lexis", "Dismissal Flag", "dismissal_flag", "extra_case_info", "character",
  "lexis", "RMSID", "rms_id", "extra_case_info", "character",
)

usethis::use_data(table_reference, overwrite = TRUE)
